### ISSUE TITLE
FYSA - In case someone gets these errors - RuntimeError: Working outside of application context. 

### ISSUE THREAD

**Issue by RaulSokolova** [mikazlopes/training-farm#7]
To fix it I had to add a couple of lines to the main.py:

Change the order for the eventlet to be the first two lines.
```
import eventlet
eventlet.monkey_patch()
import os
import sys
```

Add this line app.app_context():

```
if __name__ == "__main__":
     with app.app_context():
        SCRIPT_PATH = 'trainer.py'
        NUM_INSTANCES = 5
```

**Comment by mikazlopes** [comment]
Thank you! I am working on a new release and will also incorporate these changes.

**Comment by RaulSokolova** [comment]
Thanks @mikazlopes , looking forward to see the new capabilities... By any chance do you how any advise on rewarding the agents to sell to secure profits everyday before market closes ?

**Comment by mikazlopes** [comment]
It depends on the policy you want your agent to prioritize; you can create a flag for when the agent sells a stock at a profit which adds a multiplier to the reward at the end of the step. You will need to keep track of at what price the stock was bought and potentially a threshold on the returns percentage for which you would apply that multiplier.

**Comment by mikazlopes** [comment]
Changes added to main.py
